export const FONT_FAMILIES = [
  'Anton',
  'Bebas Neue',
  'Caveat',
  'Comfortaa',
  'Dancing Script',
  'Fredoka',
  'Heebo',
  'Josefin Sans',
  'Lobster',
  'Lora',
  'Merriweather',
  'Montserrat',
  'Oswald',
  'Pacifico',
  'Playfair Display',
  'Quicksand',
  'Raleway',
  'Roboto',
  'Roboto Slab',
  'Source Code Pro',
  'Work Sans',
];
